# docker-compose.yml (简化后)
services:
  fund_service: # 将两个服务合并成一个
    image: fund-server:latest
    container_name: fund_service # 新的容器名
    env_file:
      - .env.prod
    ports:
      - "8888:8888"
    command: >
      sh -c "python -m uvicorn src.python_cli_starter.main:api_app --host 0.0.0.0 --port 8888"
    restart: unless-stopped
    networks:
      - shared_app_net

networks:
  shared_app_net:
    external: true
    name: shared-db-network